[package]
name = "networking"
version = "0.1.0"
authors = ["julian lazaras <lazaras@pdx.edu>"]
edition = "2018"
license = "MIT"
description = "networking library that underpins the artifice network"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rsa = "*"
serde_derive = "*"
serde_json = "*"
serde = "*"
num-bigint-dig = "*"
rust-crypto = "*"
rand = "0.7.3"
tokio = {version = "*", features = ["tcp", "udp"]}
futures = "*"
